# Generated by Django 5.0.6 on 2024-05-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.IntegerField()),
                ('years', models.IntegerField()),
                ('months', models.IntegerField()),
                ('days', models.IntegerField()),
            ],
        ),
    ]
